{"timestamp":"2025-07-27T11:58:16.726803","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-07-27T11:58:16.727336","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/dvc_lightgcn_pipeline.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-27T11:58:16.998950Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-27T11:58:16.999431Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-27T11:58:17.000131Z","level":"info","event":"Current task name:run_dvc_repro","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-27T11:58:17.000654Z","level":"info","event":"Dag name:dvc_lightgcn_pipeline","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-27T11:58:16.999890","level":"info","event":"Tmp dir root location: /tmp","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-07-27T11:58:17.001166","level":"info","event":"Running command: ['/usr/bin/bash', '-c', 'cd /opt/airflow/lightgcn-recommender && dvc repro']","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-07-27T11:58:17.012648","level":"info","event":"Output:","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-07-27T11:58:18.009349","level":"info","event":"ERROR: you are not inside of a DVC repository (checked up to mount point '/opt/airflow/lightgcn-recommender')","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-07-27T11:58:18.190032","level":"info","event":"Command exited with return code 253","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-07-27T11:58:18.190784","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"AirflowException","exc_value":"Bash command failed. The command returned a non-zero exit code 253.","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":877,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1164,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/bash.py","lineno":232,"name":"execute"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-27T11:58:18.192093Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-27T11:58:18.192712Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-27T11:58:18.193266Z","level":"info","event":"Task:<Task(BashOperator): run_dvc_repro>","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-27T11:58:18.193639Z","level":"info","event":"Failure caused by Bash command failed. The command returned a non-zero exit code 253.","chan":"stdout","logger":"task"}
